import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { GlobalContexts } from "@/components/contexts/GlobalContexts";
import { ToastContainer } from "react-toastify";
import { pattaya, roboto_slab } from "@/utils/fonts/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`root ${roboto_slab.variable} ${pattaya.variable}`}>
        <GlobalContexts>{children}</GlobalContexts>
        <ToastContainer
          position="top-center"
          autoClose={3000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
        />
      </body>
    </html>
  );
}
