import type { Metadata } from "next";
import "@/app/globals.css";
import "@/style/auth/forgot-password.css";
import { GlobalContexts } from "@/components/contexts/GlobalContexts";
import Logo from "@/components/logoNav/logoNavbar";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ForgotPasswordLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section className=" content-forgot">
      <Logo />
      <GlobalContexts>{children}</GlobalContexts>
    </section>
  );
}
